---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2022: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
globals:
  window: false
  history: false
  document: false
  MouseEvent: false
  navigator: false
  requestAnimationFrame: false
  cancelAnimationFrame: false
  AudioWorkletNode: false
  AudioWorkletProcessor: false
  registerProcessor: false
extends:
  - "eslint:recommended"
  - prettier
rules:
  no-var: [error]
  no-empty: [off]
  no-unused-vars: [off]
  no-restricted-modules: [error, child_process]
  no-eval: [error]
  no-implied-eval: [error]
  strict: [warn]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
  no-case-declarations: [off]
